### ISSUE TITLE
Ошибка при соединении в COM компоненте v6.0.0 RC1 x86

### ISSUE THREAD

**Issue by HarryUniko** [diadoc/diadoccom-1c-docs#5]
Добрый день!
Пытаюсь перейти с версии COM компоненты 5.37.4 на v6.0.0 RC1 x86.
При вызове метода DiadocConnection = DiadocApi.CreateConnectionByLogin(Логин,Пароль) получаю ошибку 

![image](https://user-images.githubusercontent.com/37970297/169536416-b9a56b20-10bd-4d45-9a37-d96b5c5d58c6.png) 

На версии 5.37.4 такой ошибки не было. 
В чем может быть проблема ?

**Comment by HarryUniko** [comment]
Вопрос снимается. Нашел у себя ошибку. Неправильно задал ApiKey

**Comment by azhipaigor** [comment]
Разработка этой ветки компоненты заморожена.  Развитие компоненты продолжится в основной ветке https://developer.kontur.ru/Docs/Diadoc/Com/index.html.
