### ISSUE TITLE
Какой TypeNamedId для Доп. Соглашение к Договору ?

### ISSUE THREAD

**Issue by m-e-arutyunyan** [diadoc/diadoccom-1c-docs#6]
Подскажите, пожалуйста, Какой **TypeNamedId** для Доп. Соглашение к Договору при отправке PackageSendTask2?
Я знаю что для Договора это "Contract".
А для Доп. Соглашение к Договору не могу найти в документации.

**Comment by ButurlakinSemyon** [comment]
@m-e-arutyunyan добрый день!

SupplementaryAgreement - дополнительное соглашение к договору.
Таблица с неформализованными типами [здесь](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Enums/NonformalizedContentType.html).

**Comment by m-e-arutyunyan** [comment]
Большое Спасибо!
